from __future__ import annotations


INVENTORY_COLUMNS = [
    "stock_id",
    "food_item",
    "brand",
    "category",
    "location",
    "quantity",
    "unit",
    "servings_remaining",
    "initial_quantity",
    "initial_servings",
    "stock_status",
    "expiry_date",
    "date_added",
    "notes",
]


FOOD_WASTE_COLUMNS = [
    "waste_id",
    "stock_id",
    "food_item",
    "brand",
    "category",
    "location",
    "initial_quantity",
    "initial_unit",
    "initial_servings",
    "quantity_wasted",
    "unit",
    "servings_wasted",
    "estimated_quantity_consumed",
    "estimated_servings_consumed",
    "date_added",
    "expiry_date",
    "wasted_at",
    "waste_type",
    "waste_reason",
    "tracking_confidence",
    "notes",
]


INTAKE_HISTORY_COLUMNS = [
    "intake_id",
    "date",
    "time",
    "meal_type",
    "meal_name",
    "meal_description",
    "source",
    "amount_eaten",
    "portion_confidence",
    "total_calories_estimate",
    "total_protein_g_estimate",
    "total_carbs_g_estimate",
    "total_fat_g_estimate",
    "total_fibre_g_estimate",
    "total_sugar_g_estimate",
    "total_sodium_mg_estimate",
    "nutrition_confidence",
    "was_finished",
    "leftovers_created",
    "hunger_before",
    "hunger_after",
    "notes",
]


INTAKE_ITEMS_COLUMNS = [
    "intake_item_id",
    "intake_id",
    "food_item",
    "brand",
    "category",
    "source",
    "stock_id",
    "amount_eaten",
    "quantity_used",
    "unit",
    "servings_used",
    "calories_estimate",
    "protein_g_estimate",
    "carbs_g_estimate",
    "fat_g_estimate",
    "fibre_g_estimate",
    "sugar_g_estimate",
    "sodium_mg_estimate",
    "nutrition_confidence",
    "notes",
]


INVENTORY_CONSUMPTION_COLUMNS = [
    "consumption_id",
    "stock_id",
    "intake_id",
    "intake_item_id",
    "food_item",
    "brand",
    "category",
    "location",
    "quantity_used",
    "unit",
    "servings_used",
    "quantity_before",
    "servings_before",
    "quantity_after",
    "servings_after",
    "stock_status_before",
    "stock_status_after",
    "consumed_at",
    "consumption_type",
    "tracking_confidence",
    "notes",
]